{
 "title": "teneta-cloud",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Total [ 4xx ]",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({cluster=~`nettle-stage|nettle-prod`} | json | msg=`REQUEST_AUDIT` | status=~`4[0|7]{1}[1-3]{1}` [$__range]))"
    }
   ]
  },
  {
   "title": "Recent requests 4xx",
   "type": "logs",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 0 },
   "targets": [
    {
     "expr": "{cluster=~`nettle-stage|nettle-prod`} | json | msg=`REQUEST_AUDIT` | status=~`4[0|7]{1}[1-3]{1}`  | line_format \"status: {{.status}} cluster: {{.cluster}} uri:{{.url}} client_ip: {{.client_ip}}\""
    }
   ]
  },
  {
   "title": "Total [ 5хх ]",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({cluster=~`nettle-stage|nettle-prod`} | json | msg=`REQUEST_AUDIT` | status=~`(500|3001|3002)` [$__range]))"
    }
   ]
  },
  {
   "title": "Recent requests 5xx",
   "type": "logs",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 8 },
   "targets": [
    {
     "expr": "{cluster=~`nettle-stage|nettle-prod`} | json | msg=`REQUEST_AUDIT` | status=~`(500|3001|3002)` | line_format \"status: {{.status}} cluster: {{.cluster}} app_name: {{.app_name}}\""
    }
   ]
  }
 ]
}