{
 "title": "authzgateway",
 "time": { "from": "2024-11-18T22:00:00.000Z", "to": "2024-11-20T21:59:59.000Z" },
 "panels": [
  {
   "title": "Errors total (4xx|5xx)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 11, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({kubernetes_pod_name=~\"prod-ingress-nginx-controller.*\"} | json | status =~ `([4-5][0-9]{2})` | http_host= `authzgateway.nettlecloud.com` | http_user_agent !~ `.*Cloudflare-Healthchecks.*|.*synthetic-monitoring-agent.*` [$__range]))"
    }
   ]
  },
  {
   "title": "Requests total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 13, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({kubernetes_pod_name=~\"prod-ingress-nginx-controller.*\"} | json | http_host= `authzgateway.nettlecloud.com` | status =~ `.*` | http_user_agent !~ `.*Cloudflare-Healthchecks.*|.*synthetic-monitoring-agent.*` [$__range])) "
    }
   ]
  },
  {
   "title": "% of errors [ 4xx ]",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({kubernetes_pod_name=~\"prod-ingress-nginx-controller.*\"} | json | status =~ `4[0-9]{2}` | http_host= `authzgateway.nettlecloud.com` | http_user_agent !~ `.*Cloudflare-Healthchecks.*|.*synthetic-monitoring-agent.*` [$__range]))\n/ \nsum(count_over_time({kubernetes_pod_name=~\"prod-ingress-nginx-controller.*\"} | json | http_host= `authzgateway.nettlecloud.com` | status =~ `.*` | http_user_agent !~ `.*Cloudflare-Healthchecks.*|.*synthetic-monitoring-agent.*` [$__range])) \n* \n100"
    }
   ]
  },
  {
   "title": "Recent requests 4xx",
   "type": "logs",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 4 },
   "targets": [
    {
     "expr": "{kubernetes_pod_name=~\"prod-ingress-nginx-controller.*\"} | json | status =~ `4[0-9]{2}` | http_host= `authzgateway.nettlecloud.com` | http_user_agent !~ `.*Cloudflare-Healthchecks.*|.*synthetic-monitoring-agent.*` | line_format \"status: {{.status}} uri:{{.request_uri}}\""
    }
   ]
  },
  {
   "title": "% of errors [ 5хх ]",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({kubernetes_pod_name=~\"prod-ingress-nginx-controller.*\"} | json | status =~ `(5[0-9]{2})` | http_host= `authzgateway.nettlecloud.com` | http_user_agent !~ `.*Cloudflare-Healthchecks.*|.*synthetic-monitoring-agent.*` [$__range]))\n/ \nsum(count_over_time({kubernetes_pod_name=~\"prod-ingress-nginx-controller.*\"} | json | http_host= `authzgateway.nettlecloud.com` | status =~ `.*` | http_user_agent !~ `.*Cloudflare-Healthchecks.*|.*synthetic-monitoring-agent.*` [$__range]))\n* \n100"
    }
   ]
  },
  {
   "title": "Recent requests 5xx",
   "type": "logs",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 12 },
   "targets": [
    {
     "expr": "{kubernetes_pod_name=~\"prod-ingress-nginx-controller.*\"} | json | status =~ `(5[0-9]{2})` | http_host= `authzgateway.nettlecloud.com` | http_user_agent !~ `.*Cloudflare-Healthchecks.*|.*synthetic-monitoring-agent.*` | line_format \"{{.request_uri}} status: {{.status}}\""
    }
   ]
  }
 ]
}