{
 "title": "restricted",
 "time": { "from": "2024-11-19T22:00:00.000Z", "to": "2024-11-20T21:59:59.000Z" },
 "panels": [
  {
   "title": "Errors total (4xx|5xx)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 11, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({host=\"resource-bay\"} | json | log =~ `.*\"request_uri\":\\s*\"/restricted.*?\".*?\"status\":\\s*\"[4-5][0-9]{2}\".*`  [$__range]))"
    }
   ]
  },
  {
   "title": "Requests total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 13, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({host=\"resource-bay\"} | json | log =~ `.*\"request_uri\":\\s*\"/restricted.*?\".*?\"status\":\\s*\"([0-9]{3})\".*` [$__range]))"
    }
   ]
  },
  {
   "title": "% of errors [ 4xx ]",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({host=\"resource-bay\"} | json | log =~ `.*\"request_uri\":\\s*\"/restricted.*?\".*?\"status\":\\s*\"(4[0-9]{2})\".*` [$__range]))\n/ \nsum(count_over_time({host=\"resource-bay\"} | json | log =~ `.*\"request_uri\":\\s*\"/restricted.*?\".*?\"status\":\\s*\"([0-9]{3})\".*` [$__range]))\n* \n100"
    }
   ]
  },
  {
   "title": "Recent requests 4xx",
   "type": "logs",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 4 },
   "targets": [
    {
     "expr": "{host=\"resource-bay\"} | json | log =~ `.*\"request_uri\":\\s*\"/restricted.*?\".*?\"status\":\\s*\"(4[0-9]{2})\".*` | regexp `\\\\\"request_uri\\\\\": \\\\\"/(?P<request_uri>.*?)\\\\\",` | regexp `\\\\\"status\\\\\": \\\\\"(?P<status>.*?)\\\\\",` | line_format \"status: {{.status}} uri:{{.request_uri}} \""
    }
   ]
  },
  {
   "title": "% of errors [ 5хх ]",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({host=\"resource-bay\"} | json | log =~ `.*\"request_uri\":\\s*\"/restricted.*?\".*?\"status\":\\s*\"(5[0-9]{2})\".*` [$__range]))\n/ \nsum(count_over_time({host=\"resource-bay\"} | json | log =~ `.*\"request_uri\":\\s*\"/restricted.*?\".*?\"status\":\\s*\"([0-9]{3})\".*` [$__range]))\n* \n100"
    }
   ]
  },
  {
   "title": "Recent requests 5xx",
   "type": "logs",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 12 },
   "targets": [
    {
     "expr": "{host=\"resource-bay\"} | json | log =~ `.*\"request_uri\":\\s*\"/restricted.*?\".*?\"status\":\\s*\"(5[0-9]{2})\".*` | regexp `\\\\\"request_uri\\\\\": \\\\\"/(?P<request_uri>.*?)\\\\\",` | regexp `\\\\\"status\\\\\": \\\\\"(?P<status>.*?)\\\\\",` | line_format \"{{.request_uri}} status: {{.status}}\""
    }
   ]
  }
 ]
}