---
apiVersion: v2
name: victoria-metrics-k8s-stack
version: 0.34.0

dependencies:
  - name: victoria-metrics-k8s-stack
    version: 0.34.0
    repository: https://victoriametrics.github.io/helm-charts/
