{{- range .Values.contactPoints }}
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaContactPoint
metadata:
  name: {{ .name }}
spec:
  name: {{ .name }}
  type: {{ .type }}
  instanceSelector:
    matchLabels:
      instance: {{ $.Values.global.instanceNameLabel }}
  settings:
    {{- toYaml .settings | nindent 4 }}
  {{- if .valuesFrom }}
  valuesFrom:
    {{- range .valuesFrom }}
    - targetPath: {{ .targetPath }}
      valueFrom:
        secretKeyRef:
          name: {{ .valueFrom.secretKeyRef.name }}
          key: {{ .valueFrom.secretKeyRef.key }}
    {{- end }}
  {{- end }}
---
{{- end }}
