{{- range .Values.datasources }}
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: {{ .name }}
spec:
  instanceSelector:
    matchLabels:
      instance: {{ $.Values.global.instanceNameLabel }}
  {{- if .valuesFrom }}
  valuesFrom:
    {{- range .valuesFrom }}
    - targetPath: {{ .targetPath }}
      valueFrom:
        secretKeyRef:
          name: {{ .valueFrom.secretKeyRef.name }}
          key: {{ .valueFrom.secretKeyRef.key }}
    {{- end }}
  {{- end }}
  {{- if .plugins }}
  plugins:
    {{- range .plugins }}
    - name: {{ .name }}
      {{- if .version }}
      version: {{ .version }}
      {{- end }}
    {{- end }}
  {{- end }}
  {{- if .datasource }}
  datasource:
    name: {{ .name }}
    type: {{ .datasource.type }}
    uid: {{ .datasource.uid | default .name }}
    {{- if .datasource.access }}
    access: {{ .datasource.access }}
    {{- end }}
    {{- if .datasource.url }}
    url: {{ .datasource.url }}
    {{- end }}
    isDefault: {{ .datasource.isDefault | default false }}
    {{- if .datasource.basicAuth }}
    basicAuth: {{ .datasource.basicAuth }}
    {{- end }}
    {{- if .datasource.basicAuthUser }}
    basicAuthUser: {{ .datasource.basicAuthUser }}
    {{- end }}
    {{- if .datasource.secureJsonData }}
    secureJsonData:
      {{- range $key, $value := .datasource.secureJsonData }}
      {{ $key }}: {{ $value }}
      {{- end }}
    {{- end }}
    {{- if .datasource.jsonData }}
    jsonData:
      {{- range $key, $value := .datasource.jsonData }}
      {{ $key }}: {{ $value }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
