{{- range $key, $value := .Values.folders }}
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: {{ $key }}
spec:
  instanceSelector:
    matchLabels:
      instance: {{ $.Values.global.instanceNameLabel }}
  {{- if $value.parentFolderRef }}
  parentFolderRef: {{ $value.parentFolderRef }}
  {{- end }}
  title: {{ $value.title }}
---
{{- end }}
