apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaNotificationPolicy
metadata:
  name: nettle-notification-policy
spec:
  instanceSelector:
    matchLabels:
      instance: {{ $.Values.global.instanceNameLabel }}
  route:
    receiver: grafana-default-email
    group_by:
      - '...'
    routes:
      - receiver: OnCall Alerts
        repeat_interval: 1m
        continue: true
        object_matchers:
          - - notification_slack
            - =
            - "true"
      - receiver: Pagerduty
        continue: true
        object_matchers:
          - - notification_pagerduty
            - =
            - "true"
      - receiver: Pagerduty
        continue: true
        object_matchers:
          - - cluster
            - =
            - nettle-prod
      - receiver: Pagerduty
        continue: true
        object_matchers:
          - - nodename
            - =
            - teneta-vpn-1-prod
