apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaNotificationPolicy
metadata:
  name: nettle-notification-policy
spec:
  instanceSelector:
    matchLabels:
      instance: {{ $.Values.global.instanceNameLabel }}
  route:
    receiver: grafana-default-email
    group_by:
      - '...'
    routes:
      - receiver: grafana-cloud-oncall
        continue: true
        repeat_interval: 99w
      - receiver: nettle-pagerduty
        continue: true
        object_matchers:
          - - grafana_folder
            - =
            - openvpn-server-prod
          - - alertname
            - =~
            - OpenVPN-.*Synthetic Check
      - receiver: nettle-pagerduty
        continue: true
        object_matchers:
          - - grafana_folder
            - =
            - openvpn-server-prod
          - - alertname
            - =
            - network-utilization-<2Mbit/sec
      - receiver: nettle-pagerduty
        continue: true
        object_matchers:
          - - alertname
            - =
            - vault-secrets-webhook
