apiVersion: v1
kind: Secret
metadata:
  name: grafana-operator-common-secret
  annotations:
    vaultInjectionChecksum: "{{- $checksum := "" -}}{{- range $key, $value := .Values.vault.data -}}{{- $checksum = printf "%s%s" $checksum $value -}}{{- end -}}{{- $checksum | sha256sum }}"
{{- .Values.vault.annotations | toYaml | nindent 4 }}
stringData:
{{- with .Values.vault.data }}
{{- toYaml . | nindent 2 }}
{{- end }}
