# {{- $vaultSecretPath := "vault:secret/data/nettle/grafana/loki/gateway-htpasswd#data" -}}
{{- $vaultSecretPath := "vault:secret/data/mysql#MYSQL_ROOT_PASSWORD" -}}


apiVersion: v1
kind: Secret
metadata:
  name: loki-gateway-basic-auth
  annotations:    
    vault.security.banzaicloud.io/vault-addr: https://vault.default:8200
    vault.security.banzaicloud.io/vault-role: secretsmutation
    vault.security.banzaicloud.io/vault-tls-secret: vault-tls # pragma: allowlist secret
    vaultInjectionChecksum: {{ printf "%s" $vaultSecretPath | sha256sum }}
stringData:
  .htpasswd: {{ $vaultSecretPath }}
