apiVersion: v2
name: argo-cd
version: 7.5.2
appVersion: v2.12.3
description: A Helm chart for Argo CD, a declarative, GitOps continuous delivery tool for Kubernetes.

dependencies:
  - name: argo-cd
    version: "7.5.2"
    repository: https://argoproj.github.io/argo-helm
