argo-cd:
  configs:
    cm:
      accounts.vova: apiKey,login
      # Ignores .data changes of all secrets with a vaultInjectionChecksum annotation
      resource.customizations.ignoreDifferences.Secret: |
        jqPathExpressions:
          - '. | select(.metadata.annotations.vaultInjectionChecksum) | .data'
    rbac:
      policy.csv: |
        p, role:fluent-bit-updater, applications, get, */*, allow
        p, role:fluent-bit-updater, applications, update, */*bit, allow

        g, vova, role:fluent-bit-updater
