{{- range .Values.vmusers }}
---
apiVersion: v1
kind: Secret
metadata:
  name: vmuser-{{ .name }}-secret
  annotations:
    vault.security.banzaicloud.io/vault-addr: https://vault.default:8200
    vault.security.banzaicloud.io/vault-tls-secret: vault-tls
    vault.security.banzaicloud.io/vault-role: secretsmutation
    vaultInjectionChecksum: {{ printf "%s" .passwordSecretRef | sha256sum }}
data:
  password: {{ .passwordSecretRef | b64enc }}
type: Opaque
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMUser
metadata:
  name: {{ .name }}
spec:
  passwordRef:
    name: vmuser-{{ .name }}-secret
    key: password
  targetRefs:
    - crd:
        kind: VMSingle
        name: vm
        namespace: monitoring
      paths: ["/api/v1/write", "/vmui.*"]
{{- end }}
