{
 "title": "LogsKubernetes",
 "description": "kropyva k8s clusters ",
 "time": { "from": "now/w", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "k8s cluster",
    "query": {}
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {}
   },
   { "name": "topLogs", "label": "top n* log files", "query": "5, 10 " }
  ]
 },
 "panels": [
  {
   "title": "Sum of all producers [ Mb/h ]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum(bytes_over_time({cluster=~\"$cluster\", kubernetes_namespace_name=~\"$namespace\"}[1h])/1024/1024 > 0)"
    }
   ]
  },
  {
   "title": "By producers [ Mb/h ]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "bytes_over_time({cluster=~\"$cluster\", kubernetes_namespace_name=~\"$namespace\"}[1h])/1024/1024 > 5",
     "legendFormat": "namespace={{kubernetes_namespace_name}}, pod={{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "By producers [ Mb/time_range ]",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "topk($topLogs, bytes_over_time({cluster=~\"$cluster\", kubernetes_namespace_name=~\"$namespace\"}[$__range])/1024/1024 > 0 )",
     "legendFormat": "pod_name={{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Total by producers [ Gb/time_range ]",
   "type": "stat",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum(bytes_over_time({cluster=~\"$cluster\", kubernetes_namespace_name=~\"$namespace\"}[$__range])/1024/1024)"
    }
   ]
  }
 ]
}