{
 "title": "LogsServers",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "host",
    "query": {}
   },
   {
    "name": "service",
    "label": "service",
    "query": {}
   },
   {
    "name": "Cloudflare",
    "label": "Cloudflare",
    "query": {}
   },
   { "name": "topLogs", "label": "top n* log files", "query": "5, 10" }
  ]
 },
 "panels": [
  { "title": "Host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Sum of all producers [ Mb/h ]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum(bytes_over_time({host=~\"$host\", __stream_shard__!~\".+\"}[1h])/1024/1024 > 0)"
    }
   ]
  },
  {
   "title": "By producers [ Mb/h ]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "bytes_over_time({host=~\"$host\", __stream_shard__!~\".+\"}[1h])/1024/1024 > 0",
     "legendFormat": "environment={{environment}}, host={{host}}"
    }
   ]
  },
  {
   "title": "[ Mb/time_range ]",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "topk($topLogs, bytes_over_time({host=~\"$host\", __stream_shard__!~\".+\"}[$__range])/1024/1024 > 0 ) ",
     "legendFormat": "environment={{environment}}, host={{host}}",
     "resolution": 1
    }
   ]
  },
  {
   "title": "Total by producers [ Gb/time_range ]",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum(bytes_over_time({host=~\"$host\", __stream_shard__!~\".+\"}[$__range])/1024/1024)"
    }
   ]
  },
  { "title": "Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Sum of all producers [ Mb/h ]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum(bytes_over_time({service=~\"$service\", __stream_shard__!~\".+\"}[1h])/1024/1024 > 0) + sum(bytes_over_time({job=~\"$Cloudflare\", __stream_shard__!~\".+\"}[1h])/1024/1024 > 0)"
    }
   ]
  },
  {
   "title": "By producers [ Mb/h ]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "bytes_over_time({service=~\"$service\", __stream_shard__!~\".+\"}[1h])/1024/1024 > 1",
     "legendFormat": "environment={{environment}}, service={{service}}, host={{host}}"
    },
    {
     "expr": "bytes_over_time({job=~\"$Cloudflare\", __stream_shard__!~\".+\"}[1h])/1024/1024 > 1",
     "legendFormat": "cloudflare={{job}}"
    }
   ]
  },
  {
   "title": "By producers [ Mb/time_range ]",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "topk($topLogs, bytes_over_time({service=~\"$service\", __stream_shard__!~\".+\"}[$__range])/1024/1024 > 1 ) ",
     "legendFormat": "environment={{environment}}, host={{host}}, service={{service}}"
    },
    {
     "expr": "topk($topLogs, bytes_over_time({job=~\"$Cloudflare\", __stream_shard__!~\".+\"}[$__range])/1024/1024 > 1 ) ",
     "legendFormat": "cloudflare={{job}}"
    }
   ]
  },
  {
   "title": "Total by producers [ Gb/time_range ]",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bytes_over_time({service=~\"$service\", __stream_shard__!~\".+\"}[$__range])/1024/1024) + sum(bytes_over_time({job=~\"$Cloudflare\", __stream_shard__!~\".+\"}[$__range])/1024/1024)"
    }
   ]
  }
 ]
}